### ISSUE TITLE
render group ID on host already in use on LXC container

### ISSUE THREAD

**Issue by bnhf** [TheHellSite/proxmox_tutorials#1]
I'm attempting to use your guide to passthrough an integrated Intel GPU using your method -- which I'm very hopeful I can get to work.

On my Proxmox 7.x host, the GID for the "render" group is 103, so I'm adding this line to the .conf file for my LXC container:

```lxc.hook.pre-start: sh -c "chown 100000:100103 /dev/dri/renderD128"```

When I spin-up the container, the owner is indeed root, but the group is "input", as GID 103 in the container is already assigned to that name. What's the best way to deal with this?

Can I change the GID to another number on the host but still name it "render", and then pass that number through incremented by 100000 -- or are there consequences to this, and another approach needs to be used?

**Comment by bnhf** [comment]
I think I get it now. Nothing to do with the GID on the host, it's just the GID in the container plus 100000 -- right? So "render" in the container is GID 105, and I've changed the .conf file line to:

```lxc.hook.pre-start: sh -c "chown 100000:100105 /dev/dri/renderD128"```

I've got the permissions and ownership correct now for the entire /dev/dri directory in the container. Now I'll work on the drivers...

**Comment by TheHellSite** [comment]
> On my Proxmox 7.x host, the GID for the "render" group is 103

> I think I get it now. Nothing to do with the GID on the host, it's just the GID in the container plus 100000 -- right?

Exactly! The PVE host GID of group "render" is completely irrelevant since the host has access to device using group root anyway.
What matters is what GID group "render" has inside the LXC.
The "pre-start" command sets this GID on the PVE host so it is correct inside the LXC guest.

In case you are using different operating systems for the LXC guests the GID of group render might differ between them!
In that case it is best to...
- create a completely new group inside the LXCs with a GID choosen by you,
- set this GID in the pre-start command for all LXCs,
- and assign the service-account(s) inside the LXCs to that new group.

I am only using Arch Linux LXCs and therefore the GID of group "render" is always the same.

> Now I'll work on the drivers...

Just remember that for iGPUs there is _usually_ no need to install any drivers on the PVE host since the LXC guest is talking directly to the iGPU.

**Comment by bnhf** [comment]
@TheHellSite 

> In case you are using different operating systems for the LXC guests the GID of group render might differ between them!

Your additional clarification in the last comment was most useful -- and, I want to thank for creating this write-up in the first place. I now have hardware acceleration functioning inside a Docker container running in an unprivileged Debian 11 LXC on Promox 7.4! Very cool stuff.

I had to wade through alot of inaccurate, incomplete, outdated and just plain wrong information on this subject yesterday before I found my way here.

I may have done a few more things than required to get this working, and if you'd be so kind, I'd like to get your input on whether you think they're needed or not. Here's everything I added to the .conf file while experimenting with possibilities. You'll notice I'm changing all of the permissions recursively from /dev/dri on down to root:root, before changing card0 to root:video, and renderD128 to root:render. Permissions for all of those were nobody:nogroup in the container before those changes:

```
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.hook.pre-start: sh -c "chown -R 100000:100000 /dev/dri"
lxc.hook.pre-start: sh -c "chown 100000:100044 /dev/dri/card0"
lxc.hook.pre-start: sh -c "chown 100000:100105 /dev/dri/renderD128"
```
This gives me an exact match in the LXC, for permissions and ownership, as they originally existed on the Proxmox host:
```
root@channels0:/dev/dri# ls -la . by-path
.:
total 0
drwxr-xr-x 3 root root        100 Dec  6 08:54 .
drwxr-xr-x 8 root root        520 Dec  6 18:13 ..
drwxr-xr-x 2 root root         80 Dec  6 08:54 by-path
crw-rw---- 1 root video  226,   0 Dec  6 08:54 card0
crw-rw---- 1 root render 226, 128 Dec  6 08:54 renderD128

by-path:
total 0
drwxr-xr-x 2 root root  80 Dec  6 08:54 .
drwxr-xr-x 3 root root 100 Dec  6 08:54 ..
lrwxrwxrwx 1 root root   8 Dec  6 08:54 pci-0000:00:02.0-card -> ../card0
lrwxrwxrwx 1 root root  13 Dec  6 08:54 pci-0000:00:02.0-render -> ../renderD128
```
I installed vainfo on both the Proxmox host and the LXC, which I though was giving me the drivers, but is perhaps just showing me the drivers are present:
```
root@pve0:~# vainfo
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
As when I do an apt list --installed, the drivers appear to have been automatically installed:
```
root@channels0:/dev/dri# apt list --installed | grep va
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
i965-va-driver/oldstable,now 2.4.1+dfsg1-1 amd64 [installed,automatic]
intel-media-va-driver/oldstable,now 21.1.1+dfsg1-1 amd64 [installed,automatic]
libva-drm2/oldstable,now 2.10.0-1 amd64 [installed,automatic]
libva-wayland2/oldstable,now 2.10.0-1 amd64 [installed,automatic]
libva-x11-2/oldstable,now 2.10.0-1 amd64 [installed,automatic]
libva2/oldstable,now 2.10.0-1 amd64 [installed,automatic]
mesa-va-drivers/oldstable,now 20.3.5-1 amd64 [installed,automatic]
va-driver-all/oldstable,now 2.10.0-1 amd64 [installed,automatic]
vainfo/oldstable,now 2.10.0+ds1-1 amd64 [installed]
```
I also installed intel-gpu-tools on the host, which has been handy, as I can start a transcoded stream in the Docker container, and see hardware acceleration in action on the host:
```
intel-gpu-top -  275/ 275 MHz;    0% RC6;  1.11 Watts;      645 irqs/s

      IMC reads:     1136 MiB/s
     IMC writes:      641 MiB/s

          ENGINE      BUSY                                                                                          MI_SEMA MI_WAIT
     Render/3D/0   13.69% |███████████▉                                                                           |      7%      0%
       Blitter/0    0.80% |▋                                                                                      |      0%      0%
         Video/0    6.20% |█████▍                                                                                 |      0%      0%
  VideoEnhance/0    7.70% |██████▋                                                                                |      2%      0%
```
I also added root to video and render groups, but I'm pretty sure that was unnecessary:
```
root@channels0:/# groups root
root : root video render
```
And I believe that's it. I'll be doing this again for future LXCs that can benefit from hardware acceleration, so I want to figure out the minimum required. One thing it appears I will need to change is the GID to my own (as you outlined), as I'm transitioning to Debian 12 LXCs, and the "render" group is a different number than used in Debian 11. Should the GID I use that's available in both distros also use the name "render"?

**Comment by TheHellSite** [comment]
Well I can't really help with that as I don't have any Intel iGPUs, also this is not really an issue with my tutorial. I hope you can understand this.

What I can tell you though is that only the below lines should be necessary in the LXC config, as stated in the tutorial!
All the other lines you have right now are not needed. I tested this a lot with my AMD APU (iGPU).
```
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.hook.pre-start: sh -c "chown 100000:100989 /dev/dri/renderD128"
```

As I said I did lots of testing with my AMD APU to find out which config entries are necessary and nailed it down to the three lines above.
I also tested a lot to find out that for VA-API only `mesa libva-mesa` packages are needed.
If other packages get installed along with the two above then they are probably a dependency of another package.

> Should the GID I use, that's available in both distros, also use the name "render"?

I would strongly advise against this as the system refers to each group by name or ID. I think it wouldn't even let you create a group with a name that is already assigned.
Therefore just use some other name (f.e. pve2lxc_render) and a high GID number (f.e. 20000) inside the LXC so you do not interfere with the default system IDs.
